Fix bad builds by documenting polymer behaviors
GDGSpain/gdg.es pull request #34
Opened 2016-09-23 23:35 UTC by FredKSchott

@abdonrd we just got our new analyzer working in polymer-build, so I decided to take it for a spin. Error reporting still isn't where we want it to be, but it looks like your builds weren't completing because the analyzer was having trouble detecting your behaviors. See https://www.polymer-project.org/1.0/docs/tools/documentation#behaviors for information on how to explicitly document them.

Polymer serve is now working on both bundled and unbundled on my machine. Let me know if you're still seeing problems

2016-09-24 00:35 UTC, abdonrd commented
Thank @FredKSchott! 👏

But I just checked and the problem persists. 😕
In Safari, the both (`bundled` and `unbundled`) versions:

<img width="698" alt="screen shot 2016-09-24 at 02 31 36" src="https://cloud.githubusercontent.com/assets/1007051/18804714/4cc4dc1c-81ff-11e6-833e-307b2785c158.png">

2016-09-26 13:04 UTC, JGSolutions commented
Can this a similar issue: #67

2016-11-02 00:53 UTC, abdonrd requested changes

2016-11-02 00:53 UTC, abdonrd commented on src/app-shared-elements/gdgspain-animate-page.html
> +   * @polymerBehavior Polymer.GDGSpainAnimatePageImpl
This should not be without `Impl`?

`* @polymerBehavior Polymer.GDGSpainAnimatePage`

2016-11-02 00:53 UTC, abdonrd commented on src/app-shared-elements/gdgspain-animate-page.html
> +   * @polymerBehavior Polymer.GDGSpainAnimatePage
This should not be without name? Only:

`* @polymerBehavior`

2016-11-02 00:53 UTC, abdonrd commented on src/app-shared-elements/gdgspain-cascaded-animation.html
> +
Please, remove this extra space. 🙈

2017-01-26 13:44 UTC, merged