Http link community
GDGSpain/gdg.es pull request #42
Opened 2016-10-27 22:07 UTC by aljesusg

Add link http to groups for websites, the icon is 
[HTTP Material Icon](
https://material.io/icons/#ic_http)

We wanna have in database group.web field for GDGGranada => gdggranada.com and GDGMadrid => gdgmadrid.com

2016-10-27 22:07 UTC, aljesusg commented
@abdonrd Review this please

2016-10-27 23:25 UTC, abdonrd requested changes
Thanks for the PR!
Now I will add the links in Firebase.

2016-10-27 23:25 UTC, abdonrd commented on src/app-icons.html
> +      <g id="web"><path d="M4.5 11h-2V9H1v6h1.5v-2.5h2V15H6V9H4.5v2zm2.5-.5h1.5V15H10v-4.5h1.5V9H7v1.5zm5.5 0H14V15h1.5v-4.5H17V9h-4.5v1.5zm9-1.5H18v6h1.5v-2h2c.8 0 1.5-.7 1.5-1.5v-1c0-.8-.7-1.5-1.5-
@aljesusg can you update the icon to the ["`http`" `iron-icon`](https://github.com/PolymerElements/iron-icons/blob/master/iron-icons.html#L178)?

```html
<g id="http"><path d="M4.5 11h-2V9H1v6h1.5v-2.5h2V15H6V9H4.5v2zm2.5-.5h1.5V15H10v-4.5h1.5V9H7v1.5zm5.5 0H14V15h1.5v-4.5H17V9h-4.5v1.5zm9-1.5H18v6h1.5v-2h2c.8 0 1.5-.7 1.5-1.5v-1c0-.8-.7-1.5-1.5-1.5zm0 2.5h-2v-1h2v1z"/></g>
```

Thanks!

2016-10-27 23:25 UTC, abdonrd commented on src/app-icons.html
> +  </defs>
Get back the indent, please. 😅

2016-10-27 23:25 UTC, abdonrd commented on src/pages/groups/group-item.html
> +                  icon="web"
Update `icon="web"` to `icon="http"`, please. :)

2016-10-28 18:59 UTC, aljesusg commented on src/app-icons.html
> +      <g id="web"><path d="M4.5 11h-2V9H1v6h1.5v-2.5h2V15H6V9H4.5v2zm2.5-.5h1.5V15H10v-4.5h1.5V9H7v1.5zm5.5 0H14V15h1.5v-4.5H17V9h-4.5v1.5zm9-1.5H18v6h1.5v-2h2c.8 0 1.5-.7 1.5-1.5v-1c0-.8-.7-1.5-1.5-
Ok, I didn't see http icon in ironset !!! anyway maybe is better have the www globe icon instead http

2016-10-28 19:06 UTC, abdonrd commented on src/app-icons.html
> +      <g id="web"><path d="M4.5 11h-2V9H1v6h1.5v-2.5h2V15H6V9H4.5v2zm2.5-.5h1.5V15H10v-4.5h1.5V9H7v1.5zm5.5 0H14V15h1.5v-4.5H17V9h-4.5v1.5zm9-1.5H18v6h1.5v-2h2c.8 0 1.5-.7 1.5-1.5v-1c0-.8-.7-1.5-1.5-
What is the www globe icon? Link please! :)

Maybe you want `editor:insert-link`? Check it in the [iron-icons demo](https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html).

2016-10-28 19:10 UTC, aljesusg commented
@abdonrd Rdy for merge after build

2016-10-28 19:12 UTC, abdonrd approved these changes

2016-10-28 19:14 UTC, merged

2016-10-28 19:14 UTC, abdonrd commented
Thanks @aljesusg! 🎉

2016-10-28 19:17 UTC, abdonrd commented
Working at develop site: https://gdg-es-develop.firebaseapp.com/groups